name: ieee_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.7
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.9
  cached_network_image: ^3.3.0
  uuid: ^4.3.0
  webview_flutter: ^4.7.0
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.23.5
  smooth_page_indicator: ^1.0.0
  share_plus: ^7.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/banners/
    - assets/events/
    - assets/images/
